apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-nginx.fullname" . }}
  labels:
    {{- include "app-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30011
  selector:
    {{- include "app-nginx.selectorLabels" . | nindent 4 }}
